#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"; rm -rf /var/run/myscript.pid' SIGINT
trap 'rm -rf /var/run/myscript.pid' SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
