#!/usr/bin/env bash
#a Bash script that displays The content of the current directory
current_directory=$(pwd)
mapfile -t my_allfile < <(ls "$current_directory")

for i in "${my_allfile[@]}"; do
	my_list=$(echo "$i" | cut -d'-' -f2)
	echo "$my_list"
done
