#!/usr/bin/env bash
#a Bash script that gives you information about the school file
mydir=$(pwd)
f=school
if [ -e "$mydir/$f" ]; then
	echo "$f file exists"
	if [ -s "$mydir/$f" ]; then
	echo "$f file is not empty"
	else
	echo "$f file is empty"
	fi
	if [ -f "$mydir/$f" ]; then
	echo "$f is a regular file"
	fi
else
	echo "$f file does not exist"
fi
