#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on
output=$(ifconfig)
echo "$output" | grep -oE 'inet\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)' | cut -d" " -f2
